# Regenerate docs/CLAUDE_PIN.md (pure PowerShell — no conda needed)
# Prefer this on Windows. For conda base + Python script, use update_claude_pin.bat
param(
    [string]$Sha,
    [switch]$CheckOnly,
    [switch]$UseConda
)

$ErrorActionPreference = "Stop"
$Repo = "skcKenneth/acvrp-co2"
$Branch = "main"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

if ($UseConda) {
    $bat = Join-Path $Root "scripts\update_claude_pin.bat"
    $batArgs = @()
    if ($Sha) { $batArgs += @("--sha", $Sha) }
    if ($CheckOnly) { $batArgs += "--check-only" }
    & $bat @batArgs
    exit $LASTEXITCODE
}

if ($Sha) {
    $full = (git rev-parse $Sha).Trim()
} else {
    $full = (git rev-parse HEAD).Trim()
}
$short = (git rev-parse --short $full).Trim()

$paths = @(
    "src/nco/instance.py",
    "src/nco/model.py",
    "src/nco/baseline_am.py",
    "src/nco/trainer.py"
)

function Get-RawUrl([string]$commit, [string]$path) {
    "https://raw.githubusercontent.com/$Repo/$commit/$path"
}

$ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss") + " UTC"
$pinSelf = Get-RawUrl $full "docs/CLAUDE_PIN.md"
$sourceLines = ($paths | ForEach-Object { "- $(Get-RawUrl $full $_)" }) -join "`n"

$checks = @(
    "BatchedInstances includes ``co2_per_arc``; ``collate_instances`` returns ``co2_per_arc=co2_abs``.",
    "``model.py`` uses ``batch.co2_per_arc`` — no ``_reconstruct_co2_per_arc`` function.",
    "POMO first step: forced-first ``step_lp`` uses ``.detach()``.",
    "``baseline_am.py`` uses ``batch.co2_per_arc`` — no ``ACVRPPolicy as _AP`` CO2 reconstruction.",
    "``trainer.py`` defines ``_infer_legacy_arch()`` and uses it in ``load_checkpoint``."
)
$checkLines = (1..5 | ForEach-Object { "$_. $($checks[$_ - 1])" }) -join "`n"

$oneLiner = "Read https://raw.githubusercontent.com/$Repo/$Branch/docs/CLAUDE_PIN.md — follow it exactly (pinned commit $short). Then: [YOUR TASK]"

$body = @"
# Claude code pin (auto-generated)

> **Do not edit by hand.** Regenerated by ``scripts/update_claude_pin.ps1`` or GitHub Actions.
> Generated: $ts

## Instructions for Claude

1. Read **this file** from GitHub ``main`` (single entry point):
   ``$pinSelf``
   Or browse: https://github.com/$Repo/blob/$Branch/docs/CLAUDE_PIN.md
2. **Ignore** code from earlier chat turns, local paths (``C:\...``, ``D:\...``), or old zips.
3. Use **only** the pinned commit and raw URLs in the next section for NCO / CO2 / Methods work.
4. Reply first with: ``HEAD used = $full`` (``$short``) and pass/fail for checks 1–5 below.
   If raw content does not match this SHA, reply **STALE** and stop.

## Pinned commit

| Field | Value |
|-------|-------|
| Full SHA | ``$full`` |
| Short | ``$short`` |
| Branch | ``$Branch`` |
| Compare on GitHub | https://github.com/$Repo/commit/$full |
| Latest commits | https://github.com/$Repo/commits/$Branch |

## Verification checks (must pass on pinned SHA)

$checkLines

## Source files (raw, commit-pinned)

$sourceLines

## Regenerate (developers)

**After ``git push``** — GitHub Actions usually updates this file automatically. To refresh locally:

```powershell
cd <repo-root>
.\scripts\update_claude_pin.ps1
git add docs/CLAUDE_PIN.md
git commit -m "chore: update CLAUDE_PIN for Claude"
git push origin main
```

Pin a specific commit:

```powershell
.\scripts\update_claude_pin.ps1 -Sha <40-char-sha>
```

## One-line prompt to paste into a new Claude chat

```
$oneLiner
```
"@

$out = Join-Path $Root "docs\CLAUDE_PIN.md"
$outDir = Split-Path $out -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

$prev = if (Test-Path $out) { Get-Content $out -Raw } else { $null }
if ($prev -eq $body) {
    Write-Host "CLAUDE_PIN unchanged ($short)"
    exit 0
}
if ($CheckOnly) {
    Write-Error "CLAUDE_PIN would change (pin $short)"
    exit 1
}

Set-Content -Path $out -Value $body -Encoding utf8NoBOM -NoNewline
Add-Content -Path $out -Value "" -Encoding utf8NoBOM
Write-Host "Wrote docs/CLAUDE_PIN.md  pin=$short ($full)"

Set-Clipboard -Value $oneLiner
Write-Host "One-liner copied to clipboard."
