#!/usr/bin/env python3
"""
Regenerate docs/CLAUDE_PIN.md from the current Git HEAD (or a given SHA).

Usage:
    python scripts/update_claude_pin.py
    python scripts/update_claude_pin.py --sha abc123...
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = "skcKenneth/acvrp-co2"
BRANCH = "main"
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "CLAUDE_PIN.md"

SOURCE_PATHS = [
    "src/nco/instance.py",
    "src/nco/model.py",
    "src/nco/baseline_am.py",
    "src/nco/trainer.py",
]

CHECKS = [
    "BatchedInstances includes `co2_per_arc`; `collate_instances` returns `co2_per_arc=co2_abs`.",
    "`model.py` uses `batch.co2_per_arc` — no `_reconstruct_co2_per_arc` function.",
    "POMO first step: forced-first `step_lp` uses `.detach()`.",
    "`baseline_am.py` uses `batch.co2_per_arc` — no `ACVRPPolicy as _AP` CO2 reconstruction.",
    "`trainer.py` defines `_infer_legacy_arch()` and uses it in `load_checkpoint`.",
]


def _run(*args: str) -> str:
    return subprocess.check_output(args, cwd=ROOT, text=True).strip()


def resolve_sha(explicit: str | None) -> tuple[str, str]:
    if explicit:
        full = explicit.strip()
        if len(full) < 7:
            raise SystemExit(f"Invalid --sha: {explicit!r}")
        if len(full) < 40:
            full = _run("git", "rev-parse", full)
    else:
        full = _run("git", "rev-parse", "HEAD")
    short = _run("git", "rev-parse", "--short", full)
    return full, short


def raw_url(sha: str, path: str) -> str:
    return f"https://raw.githubusercontent.com/{REPO}/{sha}/{path}"


def build_body(sha: str, short: str) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    pin_self = raw_url(sha, "docs/CLAUDE_PIN.md")
    sources = "\n".join(f"- {raw_url(sha, p)}" for p in SOURCE_PATHS)
    checks = "\n".join(f"{i}. {c}" for i, c in enumerate(CHECKS, 1))
    commits_page = f"https://github.com/{REPO}/commits/{BRANCH}"

    return f"""# Claude code pin (auto-generated)

> **Do not edit by hand.** Regenerated by `scripts/update_claude_pin.py` or GitHub Actions.
> Generated: {ts}

## Instructions for Claude

1. Read **this file** from GitHub `main` (single entry point):
   `{pin_self}`
   Or browse: https://github.com/{REPO}/blob/{BRANCH}/docs/CLAUDE_PIN.md
2. **Ignore** code from earlier chat turns, local paths (`C:\\...`, `D:\\...`), or old zips.
3. Use **only** the pinned commit and raw URLs in the next section for NCO / CO2 / Methods work.
4. Reply first with: `HEAD used = {sha}` (`{short}`) and pass/fail for checks 1–5 below.
   If raw content does not match this SHA, reply **STALE** and stop.

## Pinned commit

| Field | Value |
|-------|-------|
| Full SHA | `{sha}` |
| Short | `{short}` |
| Branch | `{BRANCH}` |
| Compare on GitHub | https://github.com/{REPO}/commit/{sha} |
| Latest commits | {commits_page} |

## Verification checks (must pass on pinned SHA)

{checks}

## Source files (raw, commit-pinned)

{sources}

## Regenerate (developers)

**After `git push` on either machine** (optional if CI already updated this file):

```cmd
cd <repo-root>
conda activate base
scripts\\update_claude_pin.bat
```

Windows without conda: ``.\\scripts\\update_claude_pin.ps1``

Linux / GitHub Actions: ``python scripts/update_claude_pin.py``

Then: ``git add docs/CLAUDE_PIN.md`` && commit && push (optional if CI updated the file).

Pin a specific commit: ``scripts\\update_claude_pin.bat --sha <40-char-sha>``

## One-line prompt to paste into a new Claude chat

```
Read https://raw.githubusercontent.com/{REPO}/{BRANCH}/docs/CLAUDE_PIN.md — follow it exactly (pinned commit {short}). Then: [YOUR TASK]
```
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/CLAUDE_PIN.md")
    parser.add_argument(
        "--sha",
        help="Pin to this commit (full or short SHA). Default: current HEAD.",
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Exit 1 if CLAUDE_PIN.md would change (for CI).",
    )
    args = parser.parse_args()

    sha, short = resolve_sha(args.sha)
    body = build_body(sha, short)
    OUT.parent.mkdir(parents=True, exist_ok=True)

    if OUT.exists() and OUT.read_text(encoding="utf-8") == body:
        print(f"CLAUDE_PIN unchanged ({short})")
        return 0

    if args.check_only:
        print(f"CLAUDE_PIN would change (pin {short})", file=sys.stderr)
        return 1

    OUT.write_text(body, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(ROOT)}  pin={short} ({sha})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
